### ISSUE TITLE
Would be a good idea add a documentation about how to install it with debootstrap?

### ISSUE THREAD

**Issue by Camilotk** [rhino-linux/website#39]
If it looks a good idea maybe I can contribute adding a tutorial for install the distribution in "Arch Way" using deboostrap.

I not sure at moment now that would perfectly work, but I'm assuming that will since it's based on Ubuntu and it works perfectly fine in it.

I think would be great for bring Arch users that wants a more customized install experience.

**Comment by oklopfer** [comment]
Hi there, this repo is just for our website. This issue is better filed in [rhino-linux/os](https://github.com/rhino-linux/os). Also, please [join our Discord](https://discord.gg/reSvc8Ztk3), as that is where we discuss the bulk of development.
