### ISSUE TITLE
Upd: blobs.png

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/website#57]
Update the background used in the header with the new wallpaper for 2024 as set out in: https://github.com/rhino-linux/unicorn/issues/48

**Comment by 7A9Oo** [comment]
where i can contribute with some wallpapers ?

**Comment by Elsie19** [comment]
> where i can contribute with some wallpapers ?

Sorry for the (very) late reply, but you should join our discord so we can talk in real time about this.
